title: Yby's journal
description: I create premium custom websites for creative people that appreciate quality and simplicity.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://artemsheludko.com/" # the base hostname & protocol for your site, e.g. http://example.com


# Author Settings
author:
  name: Yan Boyun
  image: '/assets/img/artem-shelukod-photo.jpg'
  job: Postgraduate in UESTC
  bio:
  email: yan_boyun@163.com


# Google Analytics
google-analytics: UA-141503372-1


# Collestions
collections:
  projects:
    output: false


# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap


sass:
  sass_dir: _sass
  style: compressed


# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
